source 'https://rubygems.org'

# Provides basic authentication functionality for testing parts of your engine
#gem 'spree_auth_devise', github: 'spree/spree_auth_devise'
gem 'spree_auth_devise', :git => 'https://github.com/spree/spree_auth_devise.git', :branch => '2-1-stable'

gem 'spree_simple_sales', :path => '../spree_simple_sales'

gem 'spree_core', '2.1.3'
gemspec
